### Variables
@apiurl = http://localhost:3000

### POST user
POST {{apiurl}}/user HTTP/1.1
Content-Type: application/json

{
    "username": "carlos",
    "email": "carlos@example.com"
}

### POST magic-link
POST {{apiurl}}/user/magic-link HTTP/1.1
Content-Type: application/json

{
    "email": "carlos@example.com"
}

### POST session/authenticate
POST {{apiurl}}/user/sessions HTTP/1.1
Content-Type: application/json

{
    "token": "996f0368-43fb-4451-9d96-473b75f80299"
}