### Variables
@apiurl = http://localhost:3000

### POST user
POST {{apiurl}}/organization HTTP/1.1
Content-Type: application/json

{
    "name": "Union Lab",
    "slug": "union-lab-2",
    "ownerId": "cm7gvyoiw0000tyn73e89k52b"
}
